# =============================================================================
# FusionBench Method Configuration: PCB Merging (Conservative Parameters)
# =============================================================================
# Conservative PCB merging with lower competition parameter dropping
# =============================================================================

_target_: fusion_bench.method.pcb_merging.PCBMergingAlgorithm

# Conservative scaling factor
scaling_factor: 0.2

# Lower PCB ratio - preserve more parameters
pcb_ratio: 0.05

# Outlier clamping parameters
min_ratio: 0.0001
max_ratio: 0.0001