# =============================================================================
# FusionBench Method Configuration: Universal Model Merger (Custom Settings)
# =============================================================================
# Universal Model Merger算法，使用自定义参数配置的示例
#
# 这个配置展示了如何调整算法的各种参数
# =============================================================================

_target_: fusion_bench.method.universal_merger.UniversalMergerAlgorithm

# 融合强度系数 - 较高的alpha值意味着更强的融合
alpha: 0.7

# 重要性阈值
importance_threshold: 0.25

# 排名策略
ranking_strategy: "global"

# 随机种子
seed: 42