# =============================================================================
# FusionBench Method Configuration: Universal Model Merger (Global Ranking)
# =============================================================================
# Universal Model Merger算法，使用Global Ranking策略
#
# Global Ranking: 对整个tensor的所有元素进行排序，使用 [1, n_elements] 作为ranking scores
#
# 参数说明:
# - alphas: 各模型的融合权重，如果不指定则使用均匀权重
# - importance_threshold: 重要性阈值，用于决定冲突解决策略 (0.0-1.0)
# - ranking_strategy: 排名策略，"global" 或 "local"
# - seed: 随机种子，确保结果可重现
# =============================================================================

_target_: fusion_bench.method.universal_merger.UniversalMergerAlgorithm

# 模型融合权重 (可选，如果不指定则使用均匀权重)
alphas: null

# 重要性阈值 - 决定冲突解决策略的阈值
importance_threshold: 0.3

# 排名策略 - Global ranking
ranking_strategy: "global"

# 随机种子
seed: 42