# =============================================================================
# FusionBench Method Configuration: Universal Model Merger (Local Ranking)
# =============================================================================
# Universal Model Merger算法，使用Local Ranking策略
#
# Local Ranking: 只对冲突位置的元素进行排序，使用 linspace(0, 1) 作为ranking scores
#
# 参数说明:
# - alpha: 融合强度系数，适用于所有任务模型 (0.0-1.0)
# - importance_threshold: 重要性阈值，用于决定冲突解决策略 (0.0-1.0)
# - ranking_strategy: 排名策略，"global" 或 "local"
# - seed: 随机种子，确保结果可重现
# =============================================================================

_target_: fusion_bench.method.universal_merger.UniversalMergerAlgorithm

# 融合强度系数 - 适用于所有任务模型
alpha: 0.5

# 重要性阈值 - 决定冲突解决策略的阈值
importance_threshold: 0.3

# 排名策略 - Local ranking
ranking_strategy: "local"

# 随机种子
seed: 42