# =============================================================================
# FusionBench Analysis Configuration: SMILE Error Accumulation
# =============================================================================
# Analyzes how approximation error accumulates with gating and rank parameters.
# =============================================================================
# Measure error accumulation
_target_: fusion_bench.method.smile_upscaling.error_accumulation.ErrorAccumulationAnalysisForCLIP
gate_k: 16
k: 128
top_k: 1
